sudo: required
dist: trusty

language: go

go:
  - master

before_install:
  - sudo apt-get update
  - sudo apt-get install nodejs
  - sudo apt-get install npm

install: go get -v github.com/spf13/hugo

before_script:
  - cd exampleSite
  - npm install -g casperjs
  - phantomjs --version; casperjs --version
script:
  - hugo
  - npm version
  - phantomjs --version; casperjs --version
