# Global settings applied to the whole site.
[build]
  publish = "exampleSite/dist/"
  command = "bin/netlify.sh"

# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
  command = "bin/netlify-production.sh"
  publish = "exampleSite/dist"

# Deploy Preview context: All Deploy Previews
# will inherit these settings.
[context.deploy-preview]
  publish = "exampleSite/dist/"
  command = "bin/netlify.sh"
